[project]
name = "python-monorepo-application"
version = "0.1.0"
description = "Python Monorepo Application"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "stendhal.son", email = "stendhal.son@gmail.com" }]
requires-python = ">=3.11,<3.12"
dependencies = []

[tool.uv]
package = false
override-dependencies = ["httpx==0.25.0"]

[tool.uv.workspace]
members = ["apps/*", "packages/*"]
exclude = ["apps/user-dashboard"]
