[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "python-monorepo-application"
version = "0.1.0"
description = "Python Monorepo Application"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "order-service",
    "user-dashboard",
    "report-generator",
    "data-utils",
    "auth-helpers",
    "api-client",
    "logging-config",
    "db-models",
]

[tool.uv.sources]
order-service = { workspace = true }
user-dashboard = { workspace = true }
report-generator = { workspace = true }
data-utils = { workspace = true }
auth-helpers = { workspace = true }
api-client = { workspace = true }
logging-config = { workspace = true }
db-models = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["python_monorepo_application"]

[tool.uv.workspace]
members = ["apps/*", "packages/*"]
